package com.fyiplayer.app.download

import com.fyiplayer.app.core.CaptionTrack
import java.io.IOException
import okhttp3.HttpUrl.Companion.toHttpUrl
import okhttp3.OkHttpClient
import okhttp3.Request

/**
 * Outcome of the standalone "Download subtitles" action ([DownloadQueue.downloadSubtitles]) --
 * separate from [DownloadOption]/[com.fyiplayer.app.data.repo.DownloadItem]: a caption track is
 * its own user choice, not part of a quality the user already picked.
 */
sealed class SubtitleOutcome {
    object Saved : SubtitleOutcome()
    object NoSubtitles : SubtitleOutcome()
    /** A track exists but this app has no way to turn it into `.srt` (non-YouTube ttml/other --
     *  no `fmt=` trick off-platform). */
    object Unsupported : SubtitleOutcome()
    data class Failed(val message: String) : SubtitleOutcome()
}

/** English (exact or regional, e.g. "en-US"/"en_US") preferred, then non-auto-generated over
 *  auto, else whatever the platform listed first. Never null when [captions] is non-empty -- this
 *  path has no picker, so there must be exactly one answer. */
internal fun pickSubtitleTrack(captions: List<CaptionTrack>): CaptionTrack? {
    if (captions.isEmpty()) return null
    val english = captions.filter {
        it.languageCode == "en" || it.languageCode.startsWith("en-") || it.languageCode.startsWith("en_")
    }
    val pool = english.ifEmpty { captions }
    return pool.firstOrNull { !it.autoGenerated } ?: pool.first()
}

/**
 * Fetches [track] and returns it as SRT text, or null when this app can't produce SRT from it.
 * YouTube's timedtext endpoint answers any `fmt=` query regardless of what format [track] itself
 * reports -- forcing `fmt=vtt` always gets back convertible WebVTT. Every other platform has no
 * such trick: only a track that already reports SRT can be used, as-is.
 */
internal fun fetchSrt(client: OkHttpClient, isYouTube: Boolean, track: CaptionTrack): String? {
    if (isYouTube) {
        val body = fetchText(client, forceFmtVtt(track.url)) ?: return null
        return vttToSrt(body)
    }
    if (track.mimeType != "application/x-subrip") return null // ttml/vtt off-platform: no converter
    return fetchText(client, track.url)
}

private fun fetchText(client: OkHttpClient, url: String): String? {
    val request = Request.Builder().url(url).build()
    return try {
        client.newCall(request).execute().use { resp ->
            if (!resp.isSuccessful) null else resp.body?.string()
        }
    } catch (e: IOException) {
        null
    }
}

private fun forceFmtVtt(url: String): String =
    url.toHttpUrl().newBuilder().removeAllQueryParameters("fmt").addQueryParameter("fmt", "vtt").build().toString()

private val CUE_TIMING = Regex("""(\d{1,2}:)?\d{2}:\d{2}\.\d{3}\s*-->\s*(\d{1,2}:)?\d{2}:\d{2}\.\d{3}.*""")
private val INLINE_TAG = Regex("""<[^>]*>""")

/**
 * Pure WebVTT -> SRT conversion. Strips the `WEBVTT` header and any `NOTE`/`STYLE`/`REGION` block,
 * numbers cues, drops cue settings trailing the timing line (`align:start position:0%`), adds a
 * leading `00:` hour field when vtt omits it, swaps `.` for `,` in timestamps, and strips inline
 * tags (`<c>`, `<00:00:01.000>`). No Android/network -- plain string in, string out.
 */
internal fun vttToSrt(text: String): String {
    val lines = text.replace("\r\n", "\n").replace('\r', '\n').split("\n")
    val out = StringBuilder()
    var cueNumber = 0
    var i = 0
    while (i < lines.size) {
        val line = lines[i]
        when {
            line.isBlank() -> i++
            line.startsWith("WEBVTT") || line.startsWith("NOTE") ||
                line.startsWith("STYLE") || line.startsWith("REGION") -> {
                while (i < lines.size && lines[i].isNotBlank()) i++ // skip whole block
            }
            CUE_TIMING.matches(line) -> {
                cueNumber++
                val arrow = line.indexOf("-->")
                val start = line.substring(0, arrow).trim()
                val end = line.substring(arrow + 3).trim().substringBefore(' ').trim()
                out.append(cueNumber).append('\n')
                out.append(srtTimestamp(start)).append(" --> ").append(srtTimestamp(end)).append('\n')
                i++
                while (i < lines.size && lines[i].isNotBlank()) {
                    out.append(lines[i].replace(INLINE_TAG, "")).append('\n')
                    i++
                }
                out.append('\n')
            }
            else -> i++ // vtt cue identifier line: SRT renumbers, so it's dropped, not carried over
        }
    }
    return out.toString()
}

private fun srtTimestamp(ts: String): String =
    (if (ts.count { it == ':' } == 1) "00:$ts" else ts).replace('.', ',')
