package com.fyiplayer.app.player

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.ListItem
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.RadioButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.fyiplayer.app.core.CaptionTrack

/**
 * Caption-track picker for the item currently playing -- same shape as [QualitySheet]. [tracks] is
 * [PlaybackSession.state]'s `availableCaptions`, so this can never offer a track the current item
 * didn't actually publish. "Off" is first and matches [selectedLanguage] null (captions start OFF
 * by project rule); [onSelect] null means Off, a track means
 * [PlaybackSession.selectCaption]. [CaptionTrack.label] already carries "(auto)" for
 * auto-generated tracks, so it is shown verbatim, never re-derived from [CaptionTrack.autoGenerated].
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CaptionSheet(
    tracks: List<CaptionTrack>,
    selectedLanguage: String?,
    onSelect: (CaptionTrack?) -> Unit,
    onDismiss: () -> Unit,
) {
    ModalBottomSheet(onDismissRequest = onDismiss) {
        LazyColumn(modifier = Modifier.padding(bottom = 16.dp)) {
            item {
                ListItem(
                    headlineContent = { Text("Off") },
                    leadingContent = { RadioButton(selected = selectedLanguage == null, onClick = { onSelect(null) }) },
                    modifier = Modifier.clickable { onSelect(null) },
                )
            }
            items(tracks, key = { it.languageCode + it.label }) { track ->
                ListItem(
                    headlineContent = { Text(track.label) },
                    leadingContent = {
                        RadioButton(selected = track.languageCode == selectedLanguage, onClick = { onSelect(track) })
                    },
                    modifier = Modifier.clickable { onSelect(track) },
                )
            }
        }
    }
}
