package com.fyiplayer.app.download

import com.fyiplayer.app.core.CaptionTrack
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test

// Pure functions only -- no OkHttp/network. fetchSrt's mime/host branching is exercised through
// vttToSrt (the part it actually delegates logic-heavy work to); the HTTP fetch itself is not
// worth mocking for what is a one-line try/catch around client.newCall(...).execute().
private fun track(
    lang: String,
    mime: String = "text/vtt",
    auto: Boolean = false,
) = CaptionTrack(url = "https://example.invalid/$lang", mimeType = mime, languageCode = lang, label = lang, autoGenerated = auto)

class PickSubtitleTrackTest {
    @Test fun `no tracks yields null`() {
        assertNull(pickSubtitleTrack(emptyList()))
    }

    @Test fun `exact english wins over other languages`() {
        val picked = pickSubtitleTrack(listOf(track("fr"), track("en"), track("de")))
        assertEquals("en", picked?.languageCode)
    }

    @Test fun `a regional english variant counts as english`() {
        val picked = pickSubtitleTrack(listOf(track("fr"), track("en-US")))
        assertEquals("en-US", picked?.languageCode)
    }

    @Test fun `underscore-style regional english also counts`() {
        val picked = pickSubtitleTrack(listOf(track("fr"), track("en_GB")))
        assertEquals("en_GB", picked?.languageCode)
    }

    @Test fun `non-auto-generated english wins over auto-generated english`() {
        val picked = pickSubtitleTrack(listOf(track("en", auto = true), track("en-US", auto = false)))
        assertEquals("en-US", picked?.languageCode)
    }

    @Test fun `no english track falls back to the first track listed`() {
        val picked = pickSubtitleTrack(listOf(track("fr"), track("de")))
        assertEquals("fr", picked?.languageCode)
    }
}

class VttToSrtTest {
    @Test fun `converts a basic cue and numbers it`() {
        val vtt = """
            WEBVTT

            00:00:01.000 --> 00:00:04.000
            Hello world
        """.trimIndent()

        val srt = vttToSrt(vtt)

        assertEquals("1\n00:00:01,000 --> 00:00:04,000\nHello world\n\n", srt)
    }

    @Test fun `numbers multiple cues in order`() {
        val vtt = """
            WEBVTT

            00:00:01.000 --> 00:00:02.000
            First

            00:00:03.000 --> 00:00:04.000
            Second
        """.trimIndent()

        val srt = vttToSrt(vtt)

        assertEquals("1\n00:00:01,000 --> 00:00:02,000\nFirst\n\n2\n00:00:03,000 --> 00:00:04,000\nSecond\n\n", srt)
    }

    @Test fun `adds a leading hour field when vtt omits it`() {
        val vtt = "WEBVTT\n\n01:02.345 --> 01:05.000\nHi"
        val srt = vttToSrt(vtt)
        assertEquals("1\n00:01:02,345 --> 00:01:05,000\nHi\n\n", srt)
    }

    @Test fun `drops cue settings trailing the timing line`() {
        val vtt = "WEBVTT\n\n00:00:01.000 --> 00:00:02.000 align:start position:10%\nHi"
        val srt = vttToSrt(vtt)
        assertEquals("1\n00:00:01,000 --> 00:00:02,000\nHi\n\n", srt)
    }

    @Test fun `strips inline tags like c and timestamp karaoke tags`() {
        val vtt = "WEBVTT\n\n00:00:01.000 --> 00:00:02.000\n<c>Hello</c> <00:00:01.500>world"
        val srt = vttToSrt(vtt)
        assertEquals("1\n00:00:01,000 --> 00:00:02,000\nHello world\n\n", srt)
    }

    @Test fun `skips NOTE and STYLE blocks entirely`() {
        val vtt = """
            WEBVTT

            NOTE this is a comment
            spanning two lines

            STYLE
            ::cue { color: yellow; }

            00:00:01.000 --> 00:00:02.000
            Hi
        """.trimIndent()

        val srt = vttToSrt(vtt)

        assertEquals("1\n00:00:01,000 --> 00:00:02,000\nHi\n\n", srt)
    }

    @Test fun `drops a cue identifier line before the timing line`() {
        val vtt = "WEBVTT\n\ncue-1\n00:00:01.000 --> 00:00:02.000\nHi"
        val srt = vttToSrt(vtt)
        assertEquals("1\n00:00:01,000 --> 00:00:02,000\nHi\n\n", srt)
    }
}
